pipeline {
    agent any
    
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials-id')
        MYSQL_CREDENTIALS = credentials('mysql-credentials')
        
        NEXUS_VERSION = 'nexus3'
        NEXUS_PROTOCOL = 'http'
        NEXUS_URL = '192.168.43.183:8081' // Nexus server base URL
        NEXUS_REPOSITORY = 'tpfoyer-AdemKahouli-5BI7'  // Nexus repository name
        CREDENTIALS_ID = 'nexus-cred'      // Jenkins credentials ID for Nexus
        GROUP_ID = 'tn.esprit'  // Group ID for the artifact
    
    }
    stages {



        stage("Maven Build") {
            steps {
                 dir('tp-foyer') {
                   sh "mvn package -DskipTests=true"
                }
                
            }
        }

       
        stage('Compile') {
            steps {
                dir('tp-foyer') {
                    sh 'mvn clean compile'
                }
            }
        }

          stage("Upload to Nexus") {
            steps {
                dir('tp-foyer'){
                script {
                    def artifactId = 'tp-foyer'  // Define your artifact ID
                    def version = '5.0.0'                  // Define the version
                    def packaging = 'jar'                // Define the packaging type (e.g., jar)

                    // Correct usage of nexusArtifactUploader
                    nexusArtifactUploader(
                        nexusVersion: NEXUS_VERSION,
                        protocol: NEXUS_PROTOCOL,
                        nexusUrl: NEXUS_URL,
                        groupId: GROUP_ID,
                        artifactId: artifactId,
                        version: version,
                        repository: NEXUS_REPOSITORY,
                        credentialsId: CREDENTIALS_ID,
                        artifacts: [
                            [artifactId: artifactId,
                             classifier: '',
                             file: "target/${artifactId}-${version}.${packaging}",
                             type: packaging]
                        ]
                    )
                }
            }
            }
        }
      
        
        stage('Junit+Mock') {
            steps {
                dir('tp-foyer') {
                    sh 'mvn test'
                }
            }
        }

       stage('SonnarQube') {
            steps {
                dir('tp-foyer') {
                    withSonarQubeEnv('sq1') {
                        sh 'mvn sonar:sonar -Dsonar.java.binaries=target/classes'
                    }
                }
            }
        } 


     stage('Build Backend Docker Image') {
            steps {
                dir('tp-foyer') {
                    sh 'docker build -t tpfoyer-backend .'
                    
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                    sh 'docker tag tpfoyer-backend ademkahouli/tpfoyer-5bi7:$BUILD_NUMBER'
                    sh 'docker push ademkahouli/tpfoyer-5bi7:$BUILD_NUMBER'
                }
            }
        }
        
  stage('Stop Old Containers') {
            steps {
                sh 'docker stop mysql_db || true && docker rm mysql_db || true'
                sh 'docker stop backend_ctr || true && docker rm backend_ctr || true'
              
            }
        }
    

      stage('Deploy Application Docker Compose ') {
        steps {
        script {
            dir('tp-foyer') {
            // Update Docker Compose environment variables
            withEnv(["MYSQL_ROOT_PASSWORD=${MYSQL_CREDENTIALS_PSW}", "BUILD_NUMBER=${env.BUILD_NUMBER}"]) {
                sh 'docker-compose down'  // Stop any running containers
                sh 'docker-compose up -d' // Start containers with updated configuration
            }
                }

        }
    }
}

        
    }

 }
 
